{% set version = "2.1.3" %}
{% set gdalversion = "3.10.0" %}

package:
  name: gdal-csharp
  version: {{ version }}

source:
 url: http://download.osgeo.org/gdal/{{ gdalversion }}/gdal-{{ gdalversion }}.tar.xz
 sha256: af821a3bcf68cf085724c21c9b53605fd451d83af3c8854d8bf194638eb734a8
 
build:
  number: 1
 
requirements:
  build:
    - cmake
    - pkg-config >=0.21  # [not win]
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - swig
  host:
    - libgdal
  run:
    - libgdal
    - dotnet

test:
  files:
   - test.sh
  source_files:
   - swig/csharp/apps/GDALTest.cs


about:
  home: http://www.gdal.org
  license: MIT
  license_file: LICENSE.TXT
  summary: |
    GDAL is a translator library for raster and vector geospatial data formats that is released under an
    X/MIT style Open Source license by the Open Source Geospatial Foundation.
    This package provides the C# and Unity interface to the library.

extra:
  recipe-maintainers:
    - runette
    - bjornharrtell
