{% set version = "2.1.2" %}
{% set gdalversion = "3.9.0" %}

package:
  name: gdal-csharp
  version: {{ version }}

source:
 url: http://download.osgeo.org/gdal/{{ gdalversion }}/gdal-{{ gdalversion }}.tar.xz
 sha256: 577f80e9d14ff7c90b6bfbc34201652b4546700c01543efb4f4c3050e0b3fda2
 
build:
  number: 0
 
requirements:
  build:
    - cmake
    - pkg-config >=0.21  # [not win]
    - make  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - swig
  host:
    - libgdal
  run:
    - libgdal
    - dotnet

test:
  files:
   - test.sh
  source_files:
   - swig/csharp/apps/GDALTest.cs


about:
  home: http://www.gdal.org
  license: MIT
  license_file: LICENSE.TXT
  summary: |
    GDAL is a translator library for raster and vector geospatial data formats that is released under an
    X/MIT style Open Source license by the Open Source Geospatial Foundation.
    This package provides the C# and Unity interface to the library.

extra:
  recipe-maintainers:
    - runette
    - bjornharrtell
